[build]
  command = "npm run build" # Use npm to run the build command
  functions = "netlify/functions"
  publish = "public"

[[plugins]] # Add plugins section for Netlify plugins
  package = "@netlify/plugin-gatsby"
  [plugins.inputs]
    command = "npm run build"

[[redirects]] # Uncomment if you have client-side routing (e.g., for SPAs)
  from = "/*"
  to = "/index.html"
  status = 200

# (optional) Settings for Netlify Dev
# https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
[dev]
  command = "npm start" # Use npm to start your dev server
  port = 3000
  publish = "public" # Folder with the static content for _redirect file

# more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
